### PR TITLE
Polyfit update to reflect recent requirements

### PR DESCRIPTION
**Pull request by Ofosu-Osei**

### CODE REVIEW

**Comment by nickeubank** [comment]
THANKS! Comments soon

**Comment by nickeubank** [comment]
Does this address #1? Looks like you moved to regular confidence intervals (cool!), but it still doesn't work as something you pass into an `.add()` method (e.g., `.add(so.Lines, sor.Lowess())` or `.add(so.Lines, sor.PolyFitWithCI())` does it?

**Comment by Ofosu-Osei** [comment]
> Does this address #1? Looks like you moved to regular confidence intervals (cool!), but it still doesn't work as something you pass into an `.add()` method (e.g., `.add(so.Lines, sor.Lowess())` or `.add(so.Lines, sor.PolyFitWithCI())` does it?

You know what, I think I misinterpreted the [example](https://www.practicaldatascience.org/notebooks/class_5/week_2/20_plotting_with_seaborn.html#regression-with-confidence-intervals) you provided that returned a plot. So I thought you wanted the recipes to be called independently with arguments. I can fix this by going back to the original implementation style. Thanks!

**Comment by nickeubank** [comment]
That's poor communication on my part — the example you link was a "throw-together" that did what I wanted in terms of output, but was in no way integrated into the modular/composable framework of seaborn.objects I want to move towards.

Also: Starting July 1 you can start billing time on this. Just let me know about every two weeks how much your billing (and you may bill whatever you've put in earlier this summer).

**Comment by Ofosu-Osei** [comment]
Message acknowledged, I'll work on it as soon as possible.

**Pull request merged**
